version: "3"
services:
  api:
    image: vishalcsl/fastapi-task-manager
    depends_on:
      - postgres
    ports:
      - 80:8000
    # command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 
    # env_file:
    #   - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}

    volumes:
        - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: